<?xml version="1.0"?>
<package format="2">
  <name>tiago_pro_navigation</name>
  <version>0.0.2</version>
  <description>The tiago_pro Navigatgion metapackage</description>

  <maintainer email="antonio.brandi@pal-robotics.com">Antonio Brandi</maintainer>
  <license>Apache License 2.0</license>
  <author email="antonio.brandi@pal-robotics.com">Antonio Brandi</author>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>tiago_pro_laser_sensors</exec_depend>
  <exec_depend>tiago_pro_2dnav</exec_depend>
  <exec_depend>pal_navigation_cfg_tiago_pro</exec_depend>
  <exec_depend>tiago_pro_maps</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
